import js from '@eslint/js'
import tsPlugin from '@typescript-eslint/eslint-plugin'
import tsParser from '@typescript-eslint/parser'
import reactPlugin from 'eslint-plugin-react'
import reactHooksPlugin from 'eslint-plugin-react-hooks'
import prettierConfig from 'eslint-config-prettier'

export default [
  js.configs.recommended,
  prettierConfig,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
        // Enable type-aware linting for rules like no-unsafe-type-assertion
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        // Node globals
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        // Browser globals
        document: 'readonly',
        window: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        // Fetch API
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        Headers: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        // Timers
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        // Collections
        Promise: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        WeakMap: 'readonly',
        WeakSet: 'readonly',
        // Built-in objects
        Symbol: 'readonly',
        Proxy: 'readonly',
        Reflect: 'readonly',
        Array: 'readonly',
        Object: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        Function: 'readonly',
        // Errors
        Error: 'readonly',
        TypeError: 'readonly',
        SyntaxError: 'readonly',
        ReferenceError: 'readonly',
        RangeError: 'readonly',
        // Utilities
        JSON: 'readonly',
        Math: 'readonly',
        Date: 'readonly',
        RegExp: 'readonly',
        Intl: 'readonly',
        globalThis: 'readonly',
        undefined: 'readonly',
        NaN: 'readonly',
        Infinity: 'readonly',
        isNaN: 'readonly',
        isFinite: 'readonly',
        parseFloat: 'readonly',
        parseInt: 'readonly',
        decodeURI: 'readonly',
        decodeURIComponent: 'readonly',
        encodeURI: 'readonly',
        encodeURIComponent: 'readonly',
        // DOM Types
        HTMLElement: 'readonly',
        HTMLInputElement: 'readonly',
        HTMLFormElement: 'readonly',
        HTMLAnchorElement: 'readonly',
        HTMLElementTagNameMap: 'readonly',
        Element: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        CustomEvent: 'readonly',
        EventTarget: 'readonly',
        NodeList: 'readonly',
        Node: 'readonly',
        // React/JSX
        JSX: 'readonly',
        React: 'readonly',
        // Observers
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        ResizeObserver: 'readonly',
        MediaQueryList: 'readonly',
        MediaQueryListEvent: 'readonly',
        // Web APIs
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        XMLHttpRequest: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        Storage: 'readonly',
        HTMLStyleElement: 'readonly',
        HTMLDivElement: 'readonly',
        HTMLButtonElement: 'readonly',
        HTMLSelectElement: 'readonly',
        HTMLTextAreaElement: 'readonly',
        HTMLImageElement: 'readonly',
        HTMLSpanElement: 'readonly',
        HTMLLabelElement: 'readonly',
        HTMLTableElement: 'readonly',
        HTMLTableRowElement: 'readonly',
        HTMLTableCellElement: 'readonly',
        HTMLTableSectionElement: 'readonly',
        HTMLParagraphElement: 'readonly',
        HTMLUListElement: 'readonly',
        HTMLOListElement: 'readonly',
        HTMLLIElement: 'readonly',
        HTMLHeadingElement: 'readonly',
        HTMLPreElement: 'readonly',
        HTMLQuoteElement: 'readonly',
        DocumentFragment: 'readonly',
        Range: 'readonly',
        Selection: 'readonly',
        BeforeUnloadEvent: 'readonly',
        SubmitEvent: 'readonly',
        InputEvent: 'readonly',
        ClipboardEvent: 'readonly',
        DragEvent: 'readonly',
        WheelEvent: 'readonly',
        ProgressEvent: 'readonly',
        TransitionEvent: 'readonly',
        AnimationEvent: 'readonly',
        ErrorEvent: 'readonly',
        MessageEvent: 'readonly',
        StorageEvent: 'readonly',
        PopStateEvent: 'readonly',
        HashChangeEvent: 'readonly',
        PageTransitionEvent: 'readonly',
        EventListenerOrEventListenerObject: 'readonly',
        AddEventListenerOptions: 'readonly',
        FileList: 'readonly',
        DataTransfer: 'readonly',
        DataTransferItem: 'readonly',
        DataTransferItemList: 'readonly',
        MimeType: 'readonly',
        MimeTypeArray: 'readonly',
        global: 'readonly',
        PointerEvent: 'readonly',
        FocusEvent: 'readonly',
        Touch: 'readonly',
        TouchEvent: 'readonly',
        TouchList: 'readonly',
        DOMRect: 'readonly',
        DOMRectReadOnly: 'readonly',
        CSSStyleDeclaration: 'readonly',
        getComputedStyle: 'readonly',
        matchMedia: 'readonly',
        performance: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        queueMicrotask: 'readonly',
        structuredClone: 'readonly',
        // Vitest globals (for test files)
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        vi: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      ...reactPlugin.configs.recommended.rules,
      ...reactHooksPlugin.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'warn',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      // Prevent unsafe type assertions that narrow types (e.g., `as unknown as X` patterns)
      // This requires type-aware linting (projectService enabled above)
      // TODO: Upgrade to 'error' once existing violations are fixed
      // See: https://typescript-eslint.io/rules/no-unsafe-type-assertion/
      '@typescript-eslint/no-unsafe-type-assertion': 'warn',
      'no-constant-binary-expression': 'warn',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  // Stories files have special patterns that are valid
  {
    files: ['**/*.stories.tsx', '**/*.stories.ts'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
  // Components with intentional try-catch patterns for optional contexts
  {
    files: [
      '**/components/layout/AppBar.tsx',
      '**/components/layout/Sidebar.tsx',
      '**/components/layout/ContainerLayout.tsx',
      '**/components/list/Pagination.tsx',
      '**/components/menu/MenuItem.tsx',
      '**/components/menu/MenuItemLink.tsx',
      '**/components/menu/SubMenu.tsx',
      '**/components/edit/EditBase.tsx',
    ],
    rules: {
      'react-hooks/rules-of-hooks': 'warn',
    },
  },
  // Spec/test files can have looser rules
  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/__tests__/**'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'warn',
      'react-hooks/rules-of-hooks': 'warn',
    },
  },
  // Examples have many unsafe type assertions (they're demo code, not production)
  // Warn instead of error to allow builds while encouraging fixes
  {
    files: ['examples/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unsafe-type-assertion': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
    },
  },
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/*.config.js',
      '**/*.config.ts',
      '.admin/**',
      'storybook-static/**',
      'coverage/**',
      // Storybook config files - not part of main TypeScript project
      '.storybook/**',
      // Cypress test files (JavaScript, not TypeScript)
      '**/cypress/**',
    ],
  },
]
