// Component exports
// This file will be populated with actual components

export { Button, type ButtonProps } from './Button'

// Core components
export {
  Admin,
  Resource,
  CoreAdminContext,
  CoreAdminRoutes,
  ResourceRegistrationContext,
  type CoreAdminContextProps,
  type CoreAdminRoutesProps,
  type ResourceRegistrationContextValue,
} from './core'

// List components
export {
  List,
  ListBase,
  ListView,
  ListActions,
  ListToolbar,
  Pagination,
  RowsPerPageSelector,
  Datagrid,
  DatagridHeader,
  DatagridBody,
  DatagridRow,
  SimpleDatagridRow,
  SimpleList,
  InfiniteList,
  InfiniteListBase,
  InfiniteListView,
  DataTable,
  type ListProps,
  type ListBaseProps,
  type ListViewProps,
  type ListActionsProps,
  type ListToolbarProps,
  type PaginationProps,
  type RowsPerPageSelectorProps,
  type DatagridProps,
  type DatagridColumn,
  type RowClickHandler,
  type DatagridHeaderProps,
  type DatagridBodyProps,
  type DatagridRowProps,
  type SimpleDatagridRowProps,
  type SimpleListProps,
  type InfiniteListProps,
  type InfiniteListBaseProps,
  type InfiniteListViewProps,
  type DataTableProps,
} from './list'

// Input components
export {
  TextInput,
  NumberInput,
  PasswordInput,
  DateInput,
  DateTimeInput,
  SelectInput,
  BooleanInput,
  SelectArrayInput,
  RadioButtonGroupInput,
  CheckboxGroupInput,
  ReferenceInput,
  ReferenceArrayInput,
  AutocompleteInput,
  AutocompleteArrayInput,
  ArrayInput,
  ArrayInputContext,
  useArrayInputContext,
  SimpleFormIterator,
  TimeInput,
  FileInput,
  ImageInput,
  RichTextInput,
  TranslatableInputs,
  useTranslatableInputsContext,
  useOptionalTranslatableInputsContext,
  type TextInputProps,
  type NumberInputProps,
  type PasswordInputProps,
  type DateInputProps,
  type DateTimeInputProps,
  type SelectInputProps,
  type SelectChoice,
  type BooleanInputProps,
  type SelectArrayInputProps,
  type SelectArrayChoice,
  type RadioButtonGroupInputProps,
  type RadioChoice,
  type CheckboxGroupInputProps,
  type CheckboxChoice,
  type ReferenceInputProps,
  type ReferenceChoice,
  type ReferenceSort,
  type ReferenceArrayInputProps,
  type AutocompleteInputProps,
  type AutocompleteChoice,
  type AutocompleteArrayInputProps,
  type AutocompleteArrayChoice,
  type ArrayInputProps,
  type ArrayInputContextValue,
  type SimpleFormIteratorProps,
  type TimeInputProps,
  type FileInputProps,
  type ImageInputProps,
  type RichTextInputProps,
  type TranslatableInputsProps,
  type TranslatableInputsContextValue,
  SearchInput,
  type SearchInputProps,
} from './input'

// Field components (display)
export {
  TextField,
  NumberField,
  DateField,
  BooleanField,
  EmailField,
  UrlField,
  ReferenceField,
  ReferenceArrayField,
  ReferenceManyField,
  ReferenceManyCount,
  FunctionField,
  ArrayField,
  RichTextField,
  ImageField,
  ChipField,
  FileField,
  SelectField,
  SingleFieldList,
  TranslatableFields,
  useTranslatableFieldsContext,
  useOptionalTranslatableFieldsContext,
  type TextFieldProps,
  type NumberFieldProps,
  type DateFieldProps,
  type BooleanFieldProps,
  type EmailFieldProps,
  type UrlFieldProps,
  type ReferenceFieldProps,
  type ReferenceArrayFieldProps,
  type ReferenceManyFieldProps,
  type ReferenceManyCountProps,
  type FunctionFieldProps,
  type ArrayFieldProps,
  type RichTextFieldProps,
  type ImageFieldProps,
  type ChipFieldProps,
  type FileFieldProps,
  type FileValue,
  type SelectFieldProps,
  type SelectFieldChoice,
  type SingleFieldListProps,
  type TranslatableFieldsProps,
  type TranslatableFieldsContextValue,
  RecordField,
  type RecordFieldProps,
} from './field'

// Form components
export {
  SimpleForm,
  SimpleFormConfigurable,
  TabbedForm,
  useTabbedFormContext,
  useOptionalTabbedFormContext,
  FormTab,
  FormTabPanel,
  generateTabName,
  FormDataConsumer,
  Toolbar,
  TopToolbar,
  SaveButton,
  DeleteButton,
  type SimpleFormProps,
  type SimpleFormConfigurableProps,
  type FieldConfig,
  type TabbedFormProps,
  type TabbedFormContextValue,
  type TabInfo,
  type FormTabProps,
  type FormTabPanelProps,
  type FormDataConsumerProps,
  type FormDataConsumerRenderProps,
  type ToolbarProps,
  type TopToolbarProps,
  type SaveButtonProps,
  type DeleteButtonProps,
} from './form'

// Create components
export {
  Create,
  CreateBase,
  CreateView,
  CreateContext,
  CreateContextProvider,
  useCreateContext,
  useOptionalCreateContext,
  type CreateProps,
  type CreateBaseProps,
  type CreateViewProps,
  type CreateContextValue,
  type CreateContextProviderProps,
  type SaveHandler,
  type TransformData,
  type RedirectTo,
} from './create'

// Edit components
export {
  Edit,
  EditBase,
  EditView,
  type EditProps,
  type EditBaseProps,
  type EditViewProps,
  type EditActionsProps,
  type MutationMode,
  type Identifier,
} from './edit'

// Show components
export {
  Show,
  ShowBase,
  ShowView,
  SimpleShowLayout,
  TabbedShowLayout,
  Tab,
  useTabbedShowLayoutContext,
  useOptionalTabbedShowLayoutContext,
  generateShowTabName,
  type ShowProps,
  type ShowBaseProps,
  type ShowViewProps,
  type ShowControllerResult,
  type SimpleShowLayoutProps,
  type TabbedShowLayoutProps,
  type TabbedShowLayoutContextValue,
  type TabProps,
  type ShowTabInfo,
} from './show'

// Layout components
export {
  Layout,
  SidebarProvider,
  SidebarTrigger,
  useSidebar,
  Sidebar,
  AppBar,
  ContainerLayout,
  Title,
  TitlePortal,
  TitleContextProvider,
  useTitleContext,
  type LayoutProps,
  type SidebarContextValue,
  type SidebarProps,
  type SidebarMenuItem,
  type AppBarProps,
  type AppBarUser,
  type TitleProps,
  type TitlePortalProps,
  type TitleContextProviderProps,
  type TitleContextValue,
} from './layout'

// Menu components
export {
  Menu,
  MenuContext,
  useMenuContext,
  useMenuContextSafe,
  MenuItem,
  DashboardMenuItem,
  SubMenu,
  ResourceItem,
  type MenuProps,
  type MenuContextValue,
  type MenuItemProps,
  type BadgeVariant,
  type DashboardMenuItemProps,
  type SubMenuProps,
  type ResourceItemProps,
} from './menu'

// Auth components
export {
  LoginPage,
  LogoutButton,
  type LoginPageProps,
  type LogoutButtonProps,
} from './auth'

// Feedback components
export {
  Loading,
  Error,
  Empty,
  Confirm,
  NotificationToast,
  NotificationContainer,
  type LoadingProps,
  type ErrorProps,
  type EmptyProps,
  type ConfirmProps,
  type NotificationToastProps,
  type NotificationContainerProps,
} from './feedback'

// Button components (action buttons for navigation and data manipulation)
export {
  CreateButton,
  EditButton,
  ShowButton,
  CloneButton,
  ExportButton,
  BulkDeleteButton,
  BulkDeleteWithConfirmButton,
  BulkExportButton,
  DeleteWithConfirmButton,
  FilterButton,
  type CreateButtonProps,
  type EditButtonProps,
  type ShowButtonProps,
  type CloneButtonProps,
  type ExportButtonProps,
  type BulkDeleteButtonProps,
  type BulkDeleteWithConfirmButtonProps,
  type BulkExportButtonProps,
  type DeleteWithConfirmButtonProps,
  type FilterButtonProps,
  type FilterDefinition,
  InspectorButton,
  type InspectorButtonProps,
  InPlaceEditor,
  type InPlaceEditorProps,
  ColumnsButton,
  type ColumnsButtonProps,
} from './buttons'
